apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
    type: NodePort
    ports:
      # container port
      - targetPort: 80
      # Service port
        port: 80
        # Node port 
        nodePort: 30000
    selector:
      app: myapp
    